import bmw from "../../assets/bmw.svg";
import sneakers from "../../assets/sneakers.svg";
import Heart from "../../assets/Heart.svg";

const ProductCardData = [
  {
    id: 1,
    imgSrc: bmw,
    title: "BMW M4 Coupe: A Two-Door",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 2,
    imgSrc: bmw,
    title: "BMW M4 Coupe: A Two-Door",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 3,
    imgSrc: bmw,
    title: "BMW M4 Coupe: A Two-Door",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 4,
    imgSrc: bmw,
    title: "BMW M4 Coupe: A Two-Door",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 5,
    imgSrc: bmw,
    title: "BMW M4 Coupe: A Two-Door",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 6,
    imgSrc: bmw,
    title: "BMW M4 Coupe: A Two-Door",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 7,
    imgSrc: bmw,
    title: "BMW M4 Coupe: A Two-Door",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 8,
    imgSrc: bmw,
    title: "BMW M4 Coupe: A Two-Door",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 9,
    imgSrc: bmw,
    title: "BMW M4 Coupe: A Two-Door",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 10,
    imgSrc: bmw,
    title: "BMW M4 Coupe: A Two-Door",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 11,
    imgSrc: bmw,
    title: "BMW M4 Coupe: A Two-Door",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 12,
    imgSrc: bmw,
    title: "BMW M4 Coupe: A Two-Door",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 13,
    imgSrc: sneakers,
    title: "Adidas Yeezy 500",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 14,
    imgSrc: sneakers,
    title: "Adidas Yeezy 500",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 15,
    imgSrc: sneakers,
    title: "Adidas Yeezy 500",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 16,
    imgSrc: sneakers,
    title: "Adidas Yeezy 500",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 17,
    imgSrc: sneakers,
    title: "Adidas Yeezy 500",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 18,
    imgSrc: sneakers,
    title: "Adidas Yeezy 500",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 19,
    imgSrc: sneakers,
    title: "Adidas Yeezy 500",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 20,
    imgSrc: sneakers,
    title: "Adidas Yeezy 500",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 21,
    imgSrc: sneakers,
    title: "Adidas Yeezy 500",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 22,
    imgSrc: sneakers,
    title: "Adidas Yeezy 500",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 23,
    imgSrc: sneakers,
    title: "Adidas Yeezy 500",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
  {
    id: 24,
    imgSrc: sneakers,
    title: "Adidas Yeezy 500",
    price: "23000",
    Heart: Heart,
    heartTitle: "100",
  },
];

export default ProductCardData;
